* cd4-pchic
** GUESSFM 
Directory with own documentation, giving pipeline for GUESSFM fine mapping of autoimmune disease ImmunoChip data

** ASE
R scripts relating to ASE analysis
- IL2RA-ASE.R :: create right hand panels on IL2RA ASE figure given supplementary data items
- IL2RA-ASE+centralmem.R :: adding central memory results
** activation-analyses
 analyses comparing CD4 activated and non-activated cells.  Has its own docs.


** analyses
Other self contained scripts for figures and small analyses

- chepelev-comparison.R :: compare PCHi-C CD4 interactions to CHIA-PET interactions from Chepelev et al.
- make_modules.R :: cluster microarray data to find gene modules
** seq
scripts for processing raw sequence data
** gene_prioritisation
R and perl scripts relating to gene prioritisation.

- merge_all_summary_frag_level_results.R :: merge and format gene prioritisation results from GUESSFM and GWAS prioritisation pipelines for Additional files 7,8,9 and 10. 
- GWAS :: Pipeline for GWAS integration and annotation see also https://www.ncbi.nlm.nih.gov/pubmed/27863249 for further details.
- GUESSFM :: Pipeline for ImmunoChip GUESS Fine Mapping integration and annotation.
# Local Variables:
# firestarter: (org-md-export-to-markdown)
# End:

* License
This work is licensed under the Creative Commons Attribution 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.


# Local Variables:
# firestarter: (org-md-export-to-markdown)
# End:
